### ISSUE TITLE
Permission to propose a posible fix

### ISSUE THREAD

**Issue by cubiak** [Luncher91/IntelHex#1]
Hi Andreas, I'm Lucas Tagarelli from Argentina. I have a bug when updating the file. Could you, please, give me permission to open a new code branch to propose you the fix?. If you think the fix is ​​ok, I'm going to ask you for a pull request or if you don't think so, could you, please, explain to me what's the right use for you library?
Best Regards
Lucas

**Comment by Luncher91** [comment]
Hi Lucas,

Thank you for the time debugging the lib :-) I have added you to the repository. It would be awesome to get a proposal for a bugfix.

Kind regards,
Andreas
